// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package syncutils

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, data
func (_m *MockHandler) Handle(ctx context.Context, data interface{}) {
	_m.Called(ctx, data)
}
